### ISSUE TITLE
Duplicate API requests

### ISSUE THREAD

**Issue by simenbrekken** [acdlite/flummox-isomorphic-demo#6]
This is probably a more generic Flux question, but with getter actions how do you handle async race conditions?

E.g. an action is dispatched twice, both times the action contacts a (slow) REST API and you need to make sure that the last dispatched action supercedes the first so that a single
`successHandler/failureHandler` is invoked.

**Comment by acdlite** [comment]
Hmm, it's hard for me to know how to answer this without more specifics. One possible solution would be to pass a timestamp along with the payload so your store handler can determine how to deal with multiple actions:

``` js
// actions.js
async getThing() {
  let thing = await RESTUtils.fetchThing();
  return {
    thing,
    timestamp: Date.now()
  };
}

// store.js
handleGetThing({ thing, timestamp }) {
  if (timestamp > this.latestTimestamp) {
    this.latestTimestamp = timestamp;
    // do something
  } else {
    // do something else
  }
}
```

(This isn't something I've actually tried; just an idea.)

**Comment by simenbrekken** [comment]
On second thought these kinds of race conditions are probably best handled in the actual API module by aborting duplicate requests, that way the `success`/`failure` counterparts of an action will never get fired and thus don't need to be explicitly handled.

**Comment by ivan-kleshnin** [comment]
@simenbrekken as long as your backend is clustered this is not so easy. 
I wouldn't rely on backend to implement debounce for you, because you waste you network traffic and processor ticks to perform useless work even if duplicate requests are thrown away.

@acdlite do we have any API to temporary unsubscribe from subsequent events on actionBegin and resubscribe on actionCompleted / actionFailed? Or somehow debounce events in other way. This should be at Action level.

This demoes again how custom event architectures loose against Rx beauty...
